my_string=input('Кто ты, воин? ')
number=len(my_string)
print( 'Количество символов: ',number)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])